config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resources :movies do
  #   # /restaurants/...
  #   # collection do
  #   #   post, to: "restaurants#new"
  #   # end
  # end
  root :to => 'lists#index'
  resources :lists do
    # resources :movies, only: %i[new create]
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true
  validates :list, presence: true
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true
  validates :name, presence: true
  has_one_attached :photo
end
# List is a category
# Bookmark is a movie

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :destroy]

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    # raise
    # @list = Bookmark.find(params[:list_id])
    # @movie =
    list_id = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_bookmarks_path(list_id), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>
<%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit %>
<% end %>
<%= link_to 'Back', lists_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<!-- NAVBAR -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to 'New list', new_list_path, class: "btn btn-primary" %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>
<!-- END NAVBAR -->

<!-- BANNER -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.pinimg.com/originals/b9/bc/83/b9bc8397fa951c0002c7b397ea3ee76f.jpg);">
  <div class="container">
    <h1>Save any kind of movies</h1>
  </div>
</div>
<!-- END BANNER -->

<!-- CARD -->
<div class="container">
  <div class="cards mt-5">
    <% @lists.each do |list| %>
      <a href="<%= list_path(list) %>"> <%= cl_image_tag list.photo.key, height: 180, width: 180, crop: :fill %></a>
    <% end %>
  </div>
</div>
<!-- END CARD -->

app/views/lists/new.html.erb
<h1>New list</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>
<%= link_to 'Back', lists_path, class: "btn btn-primary" %>

app/views/lists/show.html.erb
<h1>Individual List</h1>
<%= @list.name %>
<% @list.movies.each do |movie| %>
  <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>

  <div class="container">
    <%= movie.title %>
    <div>
      <%= image_tag(movie.poster_url, size:400, class:"card-category mt-5", crop: :fill) %>
      <p><%= movie.overview %></p>
    </div>

  </div>



  <div class="container">
    <div class="card-trip">
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
      <div class="card-trip-infos">
        <div>
          <h2>Title here</h2>
          <p>Short description here!</p>
        </div>
      </div>
    </div>
  </div>



  <br>
  <div class="container">
    <div class="card-product">
      <%= image_tag(movie.poster_url) %>
      <!-- img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" / -->
      <div class="card-product-infos">
        <h2><%= movie.title %></h2>
        <p><%= movie.overview %></p>
      </div>
      <%= link_to 'Delete Bookmark',
        bookmark_path(bookmark),
        data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
        class: "btn btn-primary"
      %>
    </div>
  </div>


  <br>
  <div class="container">
    <%= link_to 'Delete Bookmark',
        bookmark_path(bookmark),
        data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
        class: "btn btn-primary"
    %>
  </div>

  <!--
  <p>
    <div class="container">
      <%= movie.title %>
      <br>
      <%= image_tag(movie.poster_url, size:200) %>
      <p>
        <%= movie.overview %>
      </p>
      <div class="container">
        <%= link_to 'Delete Bookmark',
            bookmark_path(bookmark),
            data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
            class: "btn btn-primary"
        %>
      </div>
    </div>
  </p>
  -->
<% end %>

<%= link_to 'Back', lists_path %>
<div class="container">
  <%= link_to 'Add Bookmark', new_list_bookmark_path(@list), class: "btn btn-primary" %>
</div>